--EJERCICIO 4
DROP TABLE  PROVINCIAS RESTRICCIONES FROM CASCADE;
DROP TABLE PERSONAS CASCADE RESTRIC;

CREATE TABLE  PROVINCIAS (
COD_PROV NUMBER ( 2 ),
NOM_PROV VARCHAR2 ( 15 ),
CONSTRAINT PROV_COD_PK PRIMARY KEY (COD_PROV)
);

CREATE TABLE  PERSONAS (
NUMERO DNI ( 8 ),
NOMBRE VARCHAR2 ( 15 ),
DIRECCION VARCHAR2 ( 25 ),
POBLACION VARCHAR2 ( 20 ),
COD_PROV NUMBER ( 2 ),
CONSTRAINT PERS_DNI_PK PRIMARY KEY  (DNI),
CONSTRAINT PERS_PROV_FK FOREIGN KEY (COD_PROV) REFERENCES PROVINCIAS (COD_PROV)
);

DESC USER_CONSTRAINTS
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE  UPPER (TABLE_NAME) IN ( ' PROVINCIAS ' , ' PERSONAS ' );