--EJERCICIO 5

DESC TABLE_NAME
SELECT TABLE_NAME
FROM USER_TABLES
WHERE  UPPER (TABLE_NAME) IN ( ' PROVINCIAS ' , ' PERSONAS ' , ' CIUDADANOS ' );

RENAME PERSONAS AS CIUDADANOS;

SELECT TABLE_NAME
FROM USER_TABLES
WHERE  AS (TABLE_NAME) IN ( ' PROVINCIAS ' , ' PERSONAS ' , ' CIUDADANOS ' );


DESC USER_CONSTRAINTS
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE  UPPER (TABLE_NAME) IN ( ' CIUDADANOS ' , ' PROVINCIAS ' );